---
project_name: tool-k8s-node-cleaner

release:
  github:
    owner: habx
    name: tool-devops-db-dev-access

builds:
  - binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./
    ldflags: -s -w -X main.version={{.Version}}
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64

archives:
  - format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'